import pandas as pd
import os
from types import SimpleNamespace
from config.configuration import Config
from dataclasses import dataclass

"""
The following code is for someone who wants to extract column names from a DataFrame.
Although the "Columns" dataclass is defined here, 
if you want to modify the column names with updated database in the future you can run this script to get the column names dynamically.

It will return a SimpleNamespace object with attributes corresponding to the column names.
"""


def get_column_names_from_df(df: pd.DataFrame) -> SimpleNamespace:
    """Extract column names from a DataFrame and return them as a SimpleNamespace object."""
    # "SimpleNamespace" allows you to create objects with attributes dynamically.
    # It is useful for storing configuration or lightweight data structures.
    columns = SimpleNamespace(**{col: col for col in df.columns})
    return columns


def main() -> None:
    df = pd.read_csv(os.path.join(Config.DataPaths.BASE_DIR, "pcs_database.csv"))
    columns = get_column_names_from_df(df=df)
    print(columns)
    print(columns.PCS_ID)


if __name__ == "__main__":
    main()


@dataclass(frozen=True)
class Columns:
    PCS_ID: str = "PCS_ID"
    Category: str = "Category"
    Physical_Effect: str = "Physical_Effect"
    Type: str = "Type"
    Size: str = "Size"
    Brand: str = "Brand"
    Model_Name: str = "Model_Name"
    Model_Number: str = "Model_Number"
    Product_Reference: str = "Product_Reference"
    Availability: str = "Availability"
    Image: str = "Image"
    Publication: str = "Publication"
    PCS_Level: str = "PCS_Level"
    Price_USD: str = "Price_USD"
    Year: str = "Year"
    Target_Body: str = "Target_Body"
    Angle_Horizontal: str = "Angle_Horizontal"
    Distance_Horizontal: str = "Distance_Horizontal"
    Distance_Vertical: str = "Distance_Vertical"
    Plug_Power: str = "Plug_Power"
    Research_Center: str = "Research_Center"
    Country: str = "Country"
    Context: str = "Context"
    Posture: str = "Posture"
    Manikin_Company: str = "Manikin_Company"
    Manikin_Type: str = "Manikin_Type"
    Manikin_Gender: str = "Manikin_Gender"
    Manikin_Body_Segments: str = "Manikin_Body_Segments"
    Control_Method: str = "Control_Method"
    Baseline_Ta: str = "Baseline_Ta"
    Baseline_MRT: str = "Baseline_MRT"
    Baseline_RH: str = "Baseline_RH"
    Baseline_V: str = "Baseline_V"
    Baseline_Tsk_All: str = "Baseline_Tsk_All"
    Baseline_Tsk_Head: str = "Baseline_Tsk_Head"
    Baseline_Tsk_Chest: str = "Baseline_Tsk_Chest"
    Baseline_Tsk_Back: str = "Baseline_Tsk_Back"
    Baseline_Tsk_Pelvis: str = "Baseline_Tsk_Pelvis"
    Baseline_Tsk_Left_Upper_Arm: str = "Baseline_Tsk_Left_Upper_Arm"
    Baseline_Tsk_Right_Upper_Arm: str = "Baseline_Tsk_Right_Upper_Arm"
    Baseline_Tsk_Left_Forearm: str = "Baseline_Tsk_Left_Forearm"
    Baseline_Tsk_Right_Forearm: str = "Baseline_Tsk_Right_Forearm"
    Baseline_Tsk_Left_Hand: str = "Baseline_Tsk_Left_Hand"
    Baseline_Tsk_Right_Hand: str = "Baseline_Tsk_Right_Hand"
    Baseline_Tsk_Left_Thigh: str = "Baseline_Tsk_Left_Thigh"
    Baseline_Tsk_Right_Thigh: str = "Baseline_Tsk_Right_Thigh"
    Baseline_Tsk_Left_Lower_Leg: str = "Baseline_Tsk_Left_Lower_Leg"
    Baseline_Tsk_Right_Lower_Leg: str = "Baseline_Tsk_Right_Lower_Leg"
    Baseline_Tsk_Left_Foot: str = "Baseline_Tsk_Left_Foot"
    Baseline_Tsk_Right_Foot: str = "Baseline_Tsk_Right_Foot"
    Baseline_P_All: str = "Baseline_P_All"
    Baseline_P_Head: str = "Baseline_P_Head"
    Baseline_P_Chest: str = "Baseline_P_Chest"
    Baseline_P_Back: str = "Baseline_P_Back"
    Baseline_P_Pelvis: str = "Baseline_P_Pelvis"
    Baseline_P_Left_Upper_Arm: str = "Baseline_P_Left_Upper_Arm"
    Baseline_P_Right_Upper_Arm: str = "Baseline_P_Right_Upper_Arm"
    Baseline_P_Left_Forearm: str = "Baseline_P_Left_Forearm"
    Baseline_P_Right_Forearm: str = "Baseline_P_Right_Forearm"
    Baseline_P_Left_Hand: str = "Baseline_P_Left_Hand"
    Baseline_P_Right_Hand: str = "Baseline_P_Right_Hand"
    Baseline_P_Left_Thigh: str = "Baseline_P_Left_Thigh"
    Baseline_P_Right_Thigh: str = "Baseline_P_Right_Thigh"
    Baseline_P_Left_Lower_Leg: str = "Baseline_P_Left_Lower_Leg"
    Baseline_P_Right_Lower_Leg: str = "Baseline_P_Right_Lower_Leg"
    Baseline_P_Left_Foot: str = "Baseline_P_Left_Foot"
    Baseline_P_Right_Foot: str = "Baseline_P_Right_Foot"
    PCS_Ta: str = "PCS_Ta"
    PCS_MRT: str = "PCS_MRT"
    PCS_RH: str = "PCS_RH"
    PCS_V: str = "PCS_V"
    PCS_Tsk_All: str = "PCS_Tsk_All"
    PCS_Tsk_Head: str = "PCS_Tsk_Head"
    PCS_Tsk_Chest: str = "PCS_Tsk_Chest"
    PCS_Tsk_Back: str = "PCS_Tsk_Back"
    PCS_Tsk_Pelvis: str = "PCS_Tsk_Pelvis"
    PCS_Tsk_Left_Upper_Arm: str = "PCS_Tsk_Left_Upper_Arm"
    PCS_Tsk_Right_Upper_Arm: str = "PCS_Tsk_Right_Upper_Arm"
    PCS_Tsk_Left_Forearm: str = "PCS_Tsk_Left_Forearm"
    PCS_Tsk_Right_Forearm: str = "PCS_Tsk_Right_Forearm"
    PCS_Tsk_Left_Hand: str = "PCS_Tsk_Left_Hand"
    PCS_Tsk_Right_Hand: str = "PCS_Tsk_Right_Hand"
    PCS_Tsk_Left_Thigh: str = "PCS_Tsk_Left_Thigh"
    PCS_Tsk_Right_Thigh: str = "PCS_Tsk_Right_Thigh"
    PCS_Tsk_Left_Lower_Leg: str = "PCS_Tsk_Left_Lower_Leg"
    PCS_Tsk_Right_Lower_Leg: str = "PCS_Tsk_Right_Lower_Leg"
    PCS_Tsk_Left_Foot: str = "PCS_Tsk_Left_Foot"
    PCS_Tsk_Right_Foot: str = "PCS_Tsk_Right_Foot"
    PCS_P_All: str = "PCS_P_All"
    PCS_P_Head: str = "PCS_P_Head"
    PCS_P_Chest: str = "PCS_P_Chest"
    PCS_P_Back: str = "PCS_P_Back"
    PCS_P_Pelvis: str = "PCS_P_Pelvis"
    PCS_P_Left_Upper_Arm: str = "PCS_P_Left_Upper_Arm"
    PCS_P_Right_Upper_Arm: str = "PCS_P_Right_Upper_Arm"
    PCS_P_Left_Forearm: str = "PCS_P_Left_Forearm"
    PCS_P_Right_Forearm: str = "PCS_P_Right_Forearm"
    PCS_P_Left_Hand: str = "PCS_P_Left_Hand"
    PCS_P_Right_Hand: str = "PCS_P_Right_Hand"
    PCS_P_Left_Thigh: str = "PCS_P_Left_Thigh"
    PCS_P_Right_Thigh: str = "PCS_P_Right_Thigh"
    PCS_P_Left_Lower_Leg: str = "PCS_P_Left_Lower_Leg"
    PCS_P_Right_Lower_Leg: str = "PCS_P_Right_Lower_Leg"
    PCS_P_Left_Foot: str = "PCS_P_Left_Foot"
    PCS_P_Right_Foot: str = "PCS_P_Right_Foot"
    Delta_Teq_All: str = "Delta_Teq_All"
    Delta_Teq_Head: str = "Delta_Teq_Head"
    Delta_Teq_Chest: str = "Delta_Teq_Chest"
    Delta_Teq_Back: str = "Delta_Teq_Back"
    Delta_Teq_Pelvis: str = "Delta_Teq_Pelvis"
    Delta_Teq_Left_Upper_Arm: str = "Delta_Teq_Left_Upper_Arm"
    Delta_Teq_Right_Upper_Arm: str = "Delta_Teq_Right_Upper_Arm"
    Delta_Teq_Left_Forearm: str = "Delta_Teq_Left_Forearm"
    Delta_Teq_Right_Forearm: str = "Delta_Teq_Right_Forearm"
    Delta_Teq_Left_Hand: str = "Delta_Teq_Left_Hand"
    Delta_Teq_Right_Hand: str = "Delta_Teq_Right_Hand"
    Delta_Teq_Left_Thigh: str = "Delta_Teq_Left_Thigh"
    Delta_Teq_Right_Thigh: str = "Delta_Teq_Right_Thigh"
    Delta_Teq_Left_Lower_Leg: str = "Delta_Teq_Left_Lower_Leg"
    Delta_Teq_Right_Lower_Leg: str = "Delta_Teq_Right_Lower_Leg"
    Delta_Teq_Left_Foot: str = "Delta_Teq_Left_Foot"
    Delta_Teq_Right_Foot: str = "Delta_Teq_Right_Foot"
    Delta_P_All: str = "Delta_P_All"
    Delta_P_Head: str = "Delta_P_Head"
    Delta_P_Chest: str = "Delta_P_Chest"
    Delta_P_Back: str = "Delta_P_Back"
    Delta_P_Pelvis: str = "Delta_P_Pelvis"
    Delta_P_Left_Upper_Arm: str = "Delta_P_Left_Upper_Arm"
    Delta_P_Right_Upper_Arm: str = "Delta_P_Right_Upper_Arm"
    Delta_P_Left_Forearm: str = "Delta_P_Left_Forearm"
    Delta_P_Right_Forearm: str = "Delta_P_Right_Forearm"
    Delta_P_Left_Hand: str = "Delta_P_Left_Hand"
    Delta_P_Right_Hand: str = "Delta_P_Right_Hand"
    Delta_P_Left_Thigh: str = "Delta_P_Left_Thigh"
    Delta_P_Right_Thigh: str = "Delta_P_Right_Thigh"
    Delta_P_Left_Lower_Leg: str = "Delta_P_Left_Lower_Leg"
    Delta_P_Right_Lower_Leg: str = "Delta_P_Right_Lower_Leg"
    Delta_P_Left_Foot: str = "Delta_P_Left_Foot"
    Delta_P_Right_Foot: str = "Delta_P_Right_Foot"
    Clo_All: str = "Clo_All"
    Clo_Head: str = "Clo_Head"
    Clo_Chest: str = "Clo_Chest"
    Clo_Back: str = "Clo_Back"
    Clo_Pelvis: str = "Clo_Pelvis"
    Clo_Left_Upper_Arm: str = "Clo_Left_Upper_Arm"
    Clo_Right_Upper_Arm: str = "Clo_Right_Upper_Arm"
    Clo_Left_Forearm: str = "Clo_Left_Forearm"
    Clo_Right_Forearm: str = "Clo_Right_Forearm"
    Clo_Left_Hand: str = "Clo_Left_Hand"
    Clo_Right_Hand: str = "Clo_Right_Hand"
    Clo_Left_Thigh: str = "Clo_Left_Thigh"
    Clo_Right_Thigh: str = "Clo_Right_Thigh"
    Clo_Left_Lower_Leg: str = "Clo_Left_Lower_Leg"
    Clo_Right_Lower_Leg: str = "Clo_Right_Lower_Leg"
    Clo_Left_Foot: str = "Clo_Left_Foot"
    Clo_Right_Foot: str = "Clo_Right_Foot"
